language: objective-c
matrix:
  include:
    - language: cpp
      os: osx
      osx_image: xcode12.2
      addons:
        homebrew:
          taps: david0/homebrew-audio
          update: true

script:
  # zita will be implicitly installed, ardour takes too long
  - brew install --formula `grep -l url Formula/*.rb|grep -vE 'joeboy|ardour|zita'`
  - brew test `grep -l url Formula/*.rb|grep -vE 'joeboy|ardour|zita'`

notifications:
  email:
    on_success: never
    on_failure: always
