  language: "objective-c"
  os:
    - "osx"
  before_install:
    - "brew tap ${TRAVIS_REPO_SLUG/homebrew-/}"
    - "brew update"
  script:
    - "brew install `grep -l url Formula/*.rb|grep -v joeboy`"
    - "brew test `grep -l url Formula/*.rb|grep -v joeboy`"
    - "brew install --HEAD `grep -l head Formula/*.rb`"
    - "brew test `grep -l head Formula/*.rb`"
  notifications:
    email:
      -
        on_success: "never"
        on_failure: "always"
  jobs:
    include:
      -
        language: "cpp"
        os: "osx"
